export enum TRAINING_EXPERIENCE_ENUM {
  NO = 'NO',
  TRAINING = 'TRAINING',
  FEW_WEEK_AGO = 'FEW_WEEK_AGO',
  WEEK_AGO = 'WEEK_AGO',
  MONTH_AGO = 'MONTH_AGO',
  FEW_MONTH_AGO = 'FEW_MONTH_AGO',
  YEAR_AGO = 'YEAR_AGO',
}
